name: ktlint

on:
  push:
    paths:
      - "**/*.kt"
      - "**/*.kts"
      - ".github/workflows/ktlint.yml"

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "ktlint"
        uses: "block42-blockchain-company/ktlint-action@master"